In [ ]:
# metab_2

In [1]:
import numpy as np
import pandas as pd
from biom import Table
from gemelli.rpca import rpca
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler


In [2]:
metab_1_path = 'metadata/metab_df_1_processed.csv'
metab_2_path = 'metadata/metab_df_2_processed.csv'

In [3]:
df = pd.read_csv(metab_2_path, delimiter='\t')
data = df.values  # Get the underlying numpy array

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

data += 1e-10  # To avoid log(0) issues
data_scaled += 1e-10
sample_ids = df.index.tolist()  # Get observation IDs (rows)
feature_ids = df.columns.tolist()  # Get sample IDs (columns)

# Create the biom.Table
table = Table(data.T, feature_ids, sample_ids)
table_scaled = Table(data_scaled.T, feature_ids, sample_ids)

In [4]:
dim = 3

rpca_results = rpca(table_scaled, n_components=dim)
ordination, distance = rpca_results  # Assuming the second output is loadings/components

sample_scores = ordination.samples
feature_scores = ordination.features

X_reconstructed = np.dot(sample_scores, feature_scores.T)

print(data_scaled.shape)
print(X_reconstructed.shape)

mse = mean_squared_error(data_scaled, X_reconstructed)
print(f'Reconstruction MSE: {mse}')

print(sample_scores.shape)

(744, 17354)
(744, 17354)
Reconstruction MSE: 0.009445361419029272
(744, 3)


In [5]:
dim = 5

rpca_results_2 = rpca(table_scaled, n_components=dim)
ordination_2, distance_2 = rpca_results_2  # Assuming the second output is loadings/components

sample_scores_2 = ordination_2.samples
feature_scores_2 = ordination_2.features

X_reconstructed_2 = np.dot(sample_scores_2, feature_scores_2.T)

# print(data_scaled.shape)
# print(X_reconstructed_2.shape)

mse_2 = mean_squared_error(data_scaled, X_reconstructed_2)
print(f'Reconstruction MSE: {mse_2}')

print(sample_scores_2.shape)

Reconstruction MSE: 0.009437244095420436
(744, 3)


In [6]:
dim = 10

rpca_results_3 = rpca(table_scaled, n_components=dim)
ordination_3, distance_3 = rpca_results_3  # Assuming the second output is loadings/components

sample_scores_3 = ordination_3.samples
feature_scores_3 = ordination_3.features

X_reconstructed_3 = np.dot(sample_scores_3, feature_scores_3.T)

# print(data_scaled.shape)
# print(X_reconstructed_3.shape)

mse_3 = mean_squared_error(data_scaled, X_reconstructed_3)
print(f'Reconstruction MSE: {mse_3}')

print(sample_scores_3.shape)

Reconstruction MSE: 0.009423113545124722
(744, 3)


In [ ]:
dim = 512

rpca_results_ = rpca(table_scaled, n_components=dim)
ordination_, distance_ = rpca_results_  # Assuming the second output is loadings/components

sample_scores_ = ordination_.samples
feature_scores_ = ordination_.features

X_reconstructed_ = np.dot(sample_scores_, feature_scores_.T)

# print(data_scaled.shape)
# print(X_reconstructed_.shape)

mse_ = mean_squared_error(data_scaled, X_reconstructed_)
print(f'Reconstruction MSE: {mse_}')

print(sample_scores_.shape)

In [7]:
# num = 0
# for el in rpca_results:
#     num += 1
#     print(num)
#     print(el)

# 1
# Ordination results:
# 	Method: (Robust Aitchison) RPCA Biplot (rpca_biplot)
# 	Eigvals: 3
# 	Proportion explained: 3
# 	Features: 20628x3
# 	Samples: 637x3
# 	Biplot Scores: N/A
# 	Sample constraints: N/A
# 	Feature IDs: '4326', '6697', '954', '54780', '51118', '50550', '49458', '48097', '55397', ...
# 	Sample IDs: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ...
# 2
# 637x637 distance matrix
# IDs:
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ...
# Data:
# [[0.         2.10760895 0.76862083 ... 1.68637608 1.87830878 1.36573049]
#  [2.10760895 0.         1.38467746 ... 2.07190825 0.40275515 2.29297474]
#  [0.76862083 1.38467746 0.         ... 1.73476899 1.22547324 1.6237137 ]
#  ...
#  [1.68637608 2.07190825 1.73476899 ... 0.         1.67285413 0.49748141]
#  [1.87830878 0.40275515 1.22547324 ... 1.67285413 0.         1.9087539 ]
#  [1.36573049 2.29297474 1.6237137  ... 0.49748141 1.9087539  0.        ]]

In [ ]:
# scaled:
# dim = (744, 3)
# Reconstruction MSE: 0.009445361419013932
